done testing tools/1-4

diff --git a/tools/3_prep_undeploy b/tools/3_prep_undeploy
--- a/tools/3_prep_undeploy
+++ b/tools/3_prep_undeploy
@@ -59,7 +59,7 @@ if [ "$#" -eq 3 ]; then
 
   cmd=$xsorcf' target -o '$org' -s '$targetspace
   echo $cmd
-  #if [ $do_run -eq 1 ]; then eval $cmd; fi
+  if [ $do_run -eq 1 ]; then eval $cmd; fi
   #RESULT=$?
 
   #echo 'HDI SERVICE RESULT:'$RESULT
@@ -79,31 +79,46 @@ if [ "$#" -eq 3 ]; then
   #cf env concile_utl_v0
   cmd=$xsorcf' env concile_utl_'$version_lc' | head'
   echo $cmd
-  if [ $do_run -eq 1 ]; then echo -n 'Org GUID=' ; eval $cmd; fi
+  if [ $do_run -eq 1 ]; then eval $cmd; fi
   #RESULT=$?
 
 
   #cf unbind-service concile_utl_v0 CONCILE_REG
   cmd=$xsorcf' unbind-service concile_utl_'$version_lc' CONCILE_REG'
   echo $cmd
-  if [ $do_run -eq 1 ]; then echo -n 'Org GUID=' ; eval $cmd; fi
+  if [ $do_run -eq 1 ]; then eval $cmd; fi
   #RESULT=$?
 
   #cf delete-service CONCILE_REG -f
   cmd=$xsorcf' delete-service CONCILE_REG -f'
   echo $cmd
-  if [ $do_run -eq 1 ]; then echo -n 'Org GUID=' ; eval $cmd; fi
+  if [ $do_run -eq 1 ]; then eval $cmd; fi
   #RESULT=$?
 
 
-  echo "If you are now ready to undeploy concile, use this following command."
+  echo "If you are now ready to undeploy concile, Continue to undeploy."
   echo "Note that using the --delete-services params will remove any HDI containers and their data!!!"
   echo ""
 
-  cmd=$xsorcf' undeploy conciletime -f'
+  cmd=$xsorcf' undeploy conciletime -f --delete-services'
   echo $cmd
-  #if [ $do_run -eq 1 ]; then echo -n 'Org GUID=' ; eval $cmd; fi
+  #if [ $do_run -eq 1 ]; then eval $cmd; fi
   #RESULT=$?
+
+  echo "DANGER!  The remainder of the script undeploys conciletime app but leaves the HDI container."
+
+  echo -n "Continue(y/n)? "
+  read continue_yn
+
+  if echo "$continue_yn" | grep -iq "^y" ;then
+    cmd=$xsorcf' undeploy conciletime -f'
+    echo $cmd
+    if [ $do_run -eq 1 ]; then eval $cmd; fi
+    RESULT=$?
+
+  else
+    echo "Aborting..."
+  fi
 
   echo ""
   
diff --git a/tools/4_post_undeploy b/tools/4_post_undeploy
--- a/tools/4_post_undeploy
+++ b/tools/4_post_undeploy
@@ -57,7 +57,7 @@ if [ "$#" -eq 3 ]; then
   echo UnPreparation of TargetSpace $targetspace_uc in Org: $org with Version: $version_uc Starting...
   echo ""
 
-  cmd=$xsorcf' target -o '$org' -s '$space
+  cmd=$xsorcf' target -o '$org' -s '$targetspace
   echo $cmd
   #if [ $do_run -eq 1 ]; then eval $cmd; fi
   #RESULT=$?
@@ -104,49 +104,73 @@ if [ "$#" -eq 3 ]; then
   #RESULT=$?
 
 
-  echo "Don't forget to go back and edit the "$tofile" and replace the ZZZZ with your appid."
-  #cmd='sed -e "s/ZZZZ/'$version_lc'/g" -i "" '$tofile
-  #echo $cmd
-  ##if [ $do_run -eq 1 ]; then eval $cmd; fi
-  ##RESULT=$?
-
   # DB Permission reminder
 
-  echo "You may want to remove HANA DB to create services instances in this deleted space!."
+  echo "DANGER!  The remainder of the script deletes any HDI container and removes the $targetspace space!."
 
-  cmd=$xsorcf' org '$org' --guid'
-  echo $cmd
-  if [ $do_run -eq 1 ]; then echo -n 'Org GUID=' ; eval $cmd; fi
-  #RESULT=$?
+  echo -n "Continue(y/n)? "
+  read continue_yn
 
-  #echo 'HDI SERVICE RESULT:'$RESULT
+  if echo "$continue_yn" | grep -iq "^y" ;then
 
-  cmd=$xsorcf' space '$targetspace_lc' --guid'
-  echo $cmd
-  if [ $do_run -eq 1 ]; then echo -n 'Space GUID=' ; eval $cmd; fi
-  #RESULT=$?
+    cmd=$xsorcf' delete-service CONCILE_HDB'
+    echo $cmd
+    if [ $do_run -eq 1 ]; then eval $cmd; fi
+    RESULT=$?
 
-  #echo 'HDI SERVICE RESULT:'$RESULT
+    cmd=$xsorcf' service CONCILE_HDB'
+    echo $cmd
+    if [ $do_run -eq 1 ]; then eval $cmd; fi
+    RESULT=$?
 
+      # Service creation is NOT guarenteed to happen right away
+  # Might want to add a timeout counter...
+    while [ $RESULT -eq 0 ]; do
+      echo "Sleeping for 10secs..."
+      sleep 10
 
-  # Potential target space deletion
+      if [ $xsorcf = "xs" ]; then
+        cmd=$xsorcf' service CONCILE_HDB'
+        echo $cmd
+        if [ $do_run -eq 1 ]; then eval $cmd; fi
+        RESULT=$?
+        #echo 'RESULT:'$RESULT
+      else
+        # Handle CF creation of services a bit differently
+        # cf services | grep dat368-hdi | grep "create succeeded"
+        cmd=$xsorcf' service CONCILE_HDB'
+        echo $cmd
+        if [ $do_run -eq 1 ]; then eval $cmd; fi
+        RESULT=$?
+        #echo 'RESULT:'$RESULT
+      fi
+    done
 
-  cmd=$xsorcf' delete-space '$targetspace_lc' -f'
-  echo $cmd
-  if [ $do_run -eq 1 ]; then eval $cmd; fi
-  #RESULT=$?
+    cmd=$xsorcf' target -o '$org' -s '$space
+    echo $cmd
+    if [ $do_run -eq 1 ]; then eval $cmd; fi
+    RESULT=$?
 
-  #echo 'HDI SERVICE RESULT:'$RESULT
+    # Potential target space deletion
 
-  echo ""
+    cmd=$xsorcf' delete-space '$targetspace_lc' -f'
+    echo $cmd
+    if [ $do_run -eq 1 ]; then eval $cmd; fi
+    #RESULT=$?
 
+    #echo 'HDI SERVICE RESULT:'$RESULT
 
-  tofile='Jenkinsfile'$targetspace_uc
-  echo "Don't forget to remove your Jenkins build job that pulls from the '$tofile'."
-  echo "Also, refresh your IDE and git commit/push your removed files back to your repo."
+    echo ""
 
-  echo ""
+    tofile='Jenkinsfile'$targetspace_uc
+    echo "Don't forget to remove your Jenkins build job that pulls from the '$tofile'."
+    echo "Also, refresh your IDE and git commit/push your removed files back to your repo."
+
+    echo ""
   
+  else
+    echo "Aborting..."
+  fi
   #exit 1
 
 else
